coverage:
  # small changes should not fail coverage
  precision: 1
  round: up

  ignore:
    - "tests/*"

  status:
    project:
      default:
        target: auto
      mypy:
        target: auto
        flags:
          - mypy

      tests:
        target: auto
        flags:
          - tests
