comment:
  layout: "header, diff, flags, components"
  
flag_management:
  individual_flags:
    - name: tests
      paths:
        - django_redis/
      statuses:
        - type: project

    - name: mypy
      paths:
        - django_redis/
      statuses:
        - type: project